#!/usr/bin/env python3
"""Mirror the reviewed 141 mission records without reviving old contact details.

Run after the aura-horn-torus mission source, reconciliation and coordinate checks.
This script does not fetch, geocode, publish or change the historical array.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE_URL = "https://auraofintelligence.github.io/aura-horn-torus/data/missions-australia.json"


def validate(snapshot: dict) -> None:
    if snapshot.get("schemaVersion") != "aura-missions-australia/1.0":
        raise ValueError("Unsupported reviewed mission schema")
    records = snapshot.get("records", [])
    if len(records) != 141 or {record["legacyRowNumber"] for record in records} != set(range(1, 142)):
        raise ValueError("All 141 historical records must remain traceable")
    legacy = re.findall(r"\{\s*country:\s*'((?:\\.|[^'])*)',\s*city:\s*'((?:\\.|[^'])*)',\s*type:\s*'((?:\\.|[^'])*)',", (ROOT / "missions.html").read_text(encoding="utf-8-sig"))
    if len(legacy) != 141:
        raise ValueError("The page's retained historical identities are incomplete")
    mapped = 0
    for record in records:
        number = record["legacyRowNumber"]
        old = tuple(value.replace("\\'", "'") for value in legacy[number - 1])
        if (record["country"], record["historicalCity"], record["historicalType"]) != old:
            raise ValueError(f"Historical identity changed for row {number}")
        if record["id"] != f"mission-au-{number:03d}" or record["status"] not in {"mapped", "held"}:
            raise ValueError(f"Invalid stable identity or status for row {number}")
        if any(key in record for key in ("phone", "telephone", "email", "residence", "staff")):
            raise ValueError("Only institutional office evidence belongs in this mirror")
        if record["status"] == "mapped":
            if not record["address"] or not record["coordinateSourceUrl"]:
                raise ValueError(f"Mapped row {number} lacks address or coordinate evidence")
            if not all(isinstance(record[field], (int, float)) for field in ("latitude", "longitude")):
                raise ValueError(f"Mapped row {number} lacks numeric coordinates")
            mapped += 1
        elif record["latitude"] is not None or record["longitude"] is not None:
            raise ValueError(f"Held row {number} must not contain a published map point")
        if not record["reason"] or not record["sourceUrl"] or not record["checkedAt"]:
            raise ValueError(f"Review evidence is incomplete for row {number}")
    if snapshot["counts"] != {"sourceRecords": 141, "mapped": mapped, "held": 141 - mapped}:
        raise ValueError("Snapshot counts do not reconcile with its records")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT.parent / "aura-horn-torus" / "data" / "missions-australia.json")
    parser.add_argument("--check", action="store_true", help="Validate source and confirm the checked-in mirror is identical")
    args = parser.parse_args()
    raw = args.source.read_bytes()
    snapshot = json.loads(raw.decode("utf-8-sig"))
    validate(snapshot)
    snapshot["mirror"] = {"sourceDataUrl": SOURCE_URL, "sourceSha256": sha256(raw.replace(b"\r\n", b"\n")).hexdigest(),
        "note": "Exact reviewed records mirrored from the globe project; historical contact details are not a fallback."}
    output = ROOT / "data" / "missions-reviewed.js"
    payload = json.dumps(snapshot, ensure_ascii=False, indent=2).replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    text = "// Generated by tools/sync_missions_review.py. Edit the source evidence, not this mirror.\nwindow.AUSTRALIAN_MISSIONS_REVIEW = " + payload + ";\n"
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != text:
            raise ValueError("The mission review mirror needs to be synchronised")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = output.with_suffix(".js.tmp")
        temporary.write_text(text, encoding="utf-8")
        temporary.replace(output)
    print(json.dumps({**snapshot["counts"], "checkedAddresses": sum(bool(r["address"]) for r in snapshot["records"]), "checkedAt": snapshot["checkedAt"], "mirror": "validated" if args.check else "written"}))


if __name__ == "__main__":
    main()
